### ISSUE TITLE
Master branch code not matching the latest tag

### ISSUE THREAD

**Issue by peaonunes** [cfabianski/json_translate#22]
Hey everyone! First of all great `gem`, that's being pretty useful to me!

I was looking at the readme and I was keen to try the `Enable blank value translations` however the version I have bundled in my app was crashing complaining about the `allow_blank` property. I quickly checked the master to see if the code is there and I can verify that the code was added in august last year at https://github.com/cfabianski/json_translate/commit/2b804d767e256ef8941fdc9e72d5545d620d3fdd!

Unfortunately, the last tag (`4.0.0`) seems to have been published in 2018 according to https://github.com/cfabianski/json_translate/tags. 

So should we have a `4.1.0` or something so the latest version matches what's on master?

**Comment by frantisekrokusek** [comment]
https://github.com/cfabianski/json_translate/releases/tag/v4.0.1
